<div class="line">
    <div class="box margin-bottom">
        <article class="s-12 m-7 l-12" style="text-align:justify">
            <h3 style="text-align: left;font-family: arial;border:none">Privacy Policy</h3> 
            <br> 
            It dealt and assures you that any information provided by you to jobtomoney  is protected and will be secure according to this Policy which completely based on respecting your privacy. Your data is collected and processed by us exclusively according to statutory regulations, in particular, the INDIA's Data Protection Act and Privacy and Electronic Communications Regulations. When you visit our website, data is saved on our servers in an anonymous format as is the website that you visit us from, the websites that you proceed to from our site, and your IP address. We do need some personal information from you so that you can actively participate in jobtomoney. Com. We would therefore like to request that you agree to the collection and storage of some of your data. You can revoke your consent any time by closing your account with us. This includes your:-<br><br>
            1.Name<br>
            2.Birth Date<br>
            3.Username<br>
            4.Password<br>
            5.User Image<br>
            6.Postal address<br>
            7.Contact details<br>
            8.Valid Email address<br>
            9.Mobile phone number<br><br><Br>

            This policy does not apply to the practices of companies that jobtomoney  does not own or control, or to people that jobtomoney  does not employ or manage. Usage data are personal data that identify the user, as well as information on the jobtomoney  services the user utilizes, for example your jobtomoney  user name together with the associated password and your IP address when you purchase bids or win an auction. We collect these data only to make it possible for you to use jobtomoney . The data is stored only for as long as it is necessary to process bids you have bought and auctions you have won.<br><br>
            You are requested not to give any personal information and contact details including your phone numbers and email address in Content you may post and which is viewable to others on the Website. This is to protect your privacy and to restrict communication which may possibly be unwanted/offensive/malicious/obscene or communication which may be otherwise be intrusive to you. If you did any of the same then jobtomoney  is not be liable for any of the offensive. jobtomoney .com does not encourage direct communication between users who uses the Service. Personal data such as name, address, phone no, etc. are used to process item shipment after an auction is won. Similarly, we use your data in order to inform you of marketing promotions or to enable third parties authorized by us to perform technical, logistical, or other services.<br><Br>
            Your mobile number or any other personal information will not be revealed to anyone outside of jobtomoney . jobtomoney employees who get access to this information will be under a confidentiality agreement which will ensure protection of your privacy.<br><Br>
            The information in your jobtomoney  account and in your jobtomoney profile is password protected, so that only you have access to this personal information. Please note that you are not permitted to provide your password to anyone else. jobtomoney will never ask for your password in e-mails that you receive unexpectedly or that you did not request. Please remember to log out of your account and to close your internet browser window when you leave the jobtomoney site; this is especially important if you use a PC in public locations. At present, this is the safest way to ensure that no one has access to your personal information. We assume no liability for the abuse of login data and passwords used.<br><br>
            We take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. These include internal reviews of our data collection, storage and processing practices and security measures, as well as physical security measures to guard against unauthorized access to systems where we store personal data.<br><br>
            We are strongly committed to protecting the privacy of our subscribers including bank account details and have taken necessary and reasonable measures to protect the confidentiality of subscribers' information and its transmission through the world wide web jobtomoney  shall not be held liable for disclosure of confidential information when in accordance with this Privacy Policy or Terms of Service, if any.<br><br>
            After register with jobtomoney , your account is protected by means of login information which includes a username and a password that is known only to you. Therefore, you are responsible for maintaining the confidentiality of your login information including your username and password. If you become aware of or reasonably suspect any breach of security, including compromise of your login information, it is your responsibility to immediately notify to the company. jobtomoney  communicates with you through email address that you would have specified at the time of registration. We may use this email address to send you emails related to the proper functioning of your account for instance when you receive a response to a advertisement/classified you have posted. It is possible that such emails may contain commercial messages of advertisers. To Un-subscribe from any such promotional mailer sent by the jobtomoney , you need to click on relevant link shown on the mailer to unsubscribe from the promotional database. This may take up to 48 hrs/2 working days to process.<br><br>
            jobtomoney processes personal information only for the purposes for which it was collected and in accordance with this Policy or any applicable service-specific privacy notice. We review our data collection, storage and processing practices to ensure that we only collect, store and process the personal information needed to provide or improve our services. We reserve the right to check for the accuracy of the information you provided whenever necessary. jobtomoney  assures you that we will use your e-mail address with your express consent only for the purposes stated in the Terms of Use. We will not sell your e-mail address to third parties, and we will prevent your e-mail address from being recorded by "web crawlers" or "web spiders" to the best of our ability. No 1bidding site, auction site, bids, online auction.<br><br>
            Credit card, Debit card, Net Banking or any other payment mode’s details will never be stored or handled by us. Instead, all transactions are securely handled by our payment processors. Cookies may also be assigned by the advertisers of jobtomoney.com. when you click on any of the advertisements which may be displayed on jobtomoney.com in which case such cookies are controlled by these advertisers and not by jobtomoney. Com You can view the information in your jobtomoney  account at any time and update it as necessary using your jobtomoney user name and your jobtomoney  password. Your mobile phone number for activating your account can only be changed by contacting our Customer Service.<br><br>
            Please note that this Privacy Policy may change from time to time. We will post any Policy changes on this page without giving you any prior notice. Your continued use of jobtomoney  constitutes an affirmative acknowledgement by you of the Policy changes.<br><br>
        </article>
    </div>
</div>