CREATE TABLE `_tbl_orders` (
  `OrderID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderCode` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `CustomerID` INT(11) NOT NULL,
  `OrderDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CustomerName` VARCHAR(250) CHARACTER SET utf8 NOT NULL,
  `CustomerEmailID` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `CustomerMobileNumber` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `BillingAddress1` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `BillingAddress2` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `BillingAddress3` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `BillingPincode` VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL,
  `BillingLandMark` VARCHAR(255)CHARACTER SET utf8 DEFAULT NULL,
  `OrderTotal` DOUBLE(10,2) NOT NULL DEFAULT '0.00',
  `PaymentMode` VARCHAR(255) CHARACTER SET utf8 DEFAULT '0',
  `OrderStatus` INT(11) DEFAULT '1',
  `IsPaid` INT(11) DEFAULT '0',
  `InvoiceID` INT(11) DEFAULT '0',
  `TotalUplevelCommission` INT(11) DEFAULT '0',
  PRIMARY KEY (`OrderID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `_tbl_orders_itmes` (
  `order_item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderID` INT(11) NOT NULL,
  `ProductID` INT(11) NOT NULL,
  `ProductName` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `Description` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `Qty` INT(11) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Amount` DECIMAL(10,2) NOT NULL,
  `EarningPoints` INT(11) DEFAULT '0',
  `TotalEarningPoints` INT(11) DEFAULT '0',
  `ProductCommission` INT(11) DEFAULT '0',
  `TotalCommission` INT(11) DEFAULT '0',
  PRIMARY KEY (`order_item_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `_tbl_customer` (
  `CustomerID` INT(11) NOT NULL AUTO_INCREMENT,
  `CustomerCode` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `CustomerName` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `EmailID` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `MobileNumber` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `Password` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `AddressLine1` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `AddressLine2` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `AddressLine3` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `PostalCode` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `LandMark` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `IsActive` INT(11) DEFAULT '1',
  `CreatedOn` DATETIME DEFAULT NULL,
  `Referral` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  `CreatedBy` INT(11) DEFAULT NULL,
  `ManualCreate` INT(11) DEFAULT '0',
  PRIMARY KEY (`CustomerID`)
) ENGINE=INNODB AUTO_INCREMENT=30000 DEFAULT CHARSET=utf8;
