<?php include_once("header.php"); ?>
<div class="main-panel" style="width: 100%;height:auto !important">
    <div class="container">
        <div class="page-inner">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2>Terms And Conditions</h2> <br>
                             <b>1. ACCEPTANCE OF TERMS</b><br>
                             Klx.co.in provides a collection of online resources, including classified ads, responses, reminders & updates (referred to hereafter as "the Service") subject to the following terms and conditions ("Terms"). By using the Service in any way, you are agreeing to comply with these Terms. In addition, when using particular classifiedz.in services, you agree to abide by any applicable posted guidelines for all klx.co..in services, which may change from time to time.<br><br>
                             Should you object to any term or condition of these Terms, any guidelines, or any subsequent modifications thereto or become dissatisfied with klx.co.in. in any way, your only recourse is to immediately discontinue use of classifiedz.in. You are, however, encouraged to inform/complain to our contact us team who will do their best to address your concern(s).<br><br>
                             
                             <b>2. MODIFICATIONS TO THIS AGREEMENT</b><br>
                             We reserve the right, at our sole discretion, to change, modify or otherwise alter these terms and conditions at any time. Such modifications shall become effective immediately upon the posting thereof. You must review this agreement on a regular basis to keep yourself apprised of any changes.<br><br>

                             <b>3. CONTENT</b><br>
                             You understand that all postings, ads, messages, text, files, images, photos, video, sounds, or other materials ("Content") posted on, transmitted through, or linked from the Service, are the sole responsibility of the person from whom such Content originated. More specifically, you are entirely responsible for all content that you post, email or otherwise make available via the Service. You understand that klx.co.in does not control, and is not responsible for Content made available through the Service, and that by using the Service, you may be exposed to Content that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. Furthermore, the klx.co.in site and Content available through the Service may contain links to other websites, which are completely independent of klx.co.in.<br><br>
                             Klx.co.in makes no representation or warranty as to the accuracy, completeness or authenticity of the information contained in any such site.<br><br>
                             Your linking to any other website is at your own risk. You agree that you must evaluate, and bear all risks associated with, the use of any Content, that you may not rely on said Content, and that under no circumstances will c.co..in be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed or otherwise made available via the Service. - By having your mobile number listed on klx.co.in, you agree to receive communication from third parties who may wish to contact you through the site.<br><br>
                             You acknowledge that klx.co.in does not always pre-screen or approve Content (unless specified), but that klx.co..in shall have the right (but not the obligation) in its sole discretion to refuse, delete or move any Content that is available via the Service, for violating the letter or spirit of the Terms or for any other reason.<br><br>

                             <b>4. THIRD PARTY CONTENT, SITES, AND SERVICES</b><br>
                             The klx.co.in site and Content available through the Service may contain features and functionalities that may link you or provide you with access to third party content which is completely independent of klx.co..in, including web sites, directories, servers, networks, systems, information and databases, applications, software, programs, products or services, and the Internet as a whole.<br><br>
                             Your interactions with organizations and/or individuals found on or through the Service, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals.<br><br>
                             You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline communication/transaction with any of these third parties.<br><br>
                             You agree that klx.co.in shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you understand and agree that klx.co.in is under no obligation to become involved. In the event that you have a dispute with one or more other third parties, you hereby release klx.co.in, its officers, employees, agents and successors in rights from claims, demands and damages (actual and consequential) of every kind or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such disputes and / or our service.    <br><br>

                             <b>5. NOTIFICATION OF CLAIMS OF INFRINGEMENT </b><br>
                             If you believe that your work has been copied in a way that constitutes copyright infringement, or your intellectual property rights have been otherwise violated, please notify us at reach [at] klx.co.in.<br><br>

                             <b>6. PRIVACY AND INFORMATION DISCLOSURE</b><br>
                             Klx.co.in has established a Privacy Policy to explain to users how their information is collected and used, which is located at the following web address:http://www.klx.in/Privacy<br><br>
                             Your use of the klx.co.in website or the Service signifies acknowledgement of and agreement to our Privacy Policy. You further acknowledge and agree that klx.co.in may, in its sole discretion, preserve or disclose your Content, as well as your information, such as email addresses, IP addresses, timestamps, and other user information, if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: comply with legal process; enforce these Terms; respond to claims that any Content violates the rights of third-parties; respond to claims that contact information (e.g. phone number, street address) of a third-party has been posted or transmitted without their consent or as a form of harassment; protect the rights, property, or personal safety of klx.co.in, its users or the general public. In the event that you provide any information, including personal information, in response to any marketing communication, the said information may be shared with the third parties. Please exercise due care before entering into any transaction. Provisions mentioned in ause 4 will apply to such information provided.<br><br>
                             
                             <b>7. CONDUCT</b><br>
                             You agree not to post, email, or otherwise make available Content:<br><br>
                             a) that is unlawful, harmful, threatening, abusive, harassing, defamatory, libellous, invasive of another's privacy, or is harmful to minors in any way;<br>
                             b) that is pornographic in nature<br>
                             c) that harasses, degrades, intimidates or is hateful toward an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;<br>
                             d) that impersonates any person or entity, including, but not limited to, a klx employee, or falsely states or otherwise misrepresents your affiliation with a person or entity (this provision does not apply to messages that are lawful non-deceptive parodies of public figures.);<br>
                             e) that includes personal or identifying information about another person without that person's explicit consent;<br>
                             f) that is false, deceptive, misleading, deceitful, misinformative, or constitutes "bait and switch";<br>
                             g) that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party, or Content that you do not have a right to make available under any law or under contractual or fiduciary relationships;<br>
                             h) that constitutes or contains "affiliate marketing," "link referral code," "junk mail," "spam," "chain letters," "pyramid schemes," or unsolicited commercial advertisement;<br>
                             i) that constitutes or contains any form of advertising or solicitation if: posted in areas of the klx.co..in sites which are not designated for such purposes; or emailed to klx.co.in users who have not indicated in writing that it is ok to contact them about other services, products or commercial interests.<br>
                             j) that includes links to commercial services or web sites, except as allowed in "services";<br>
                             k) that advertises any illegal service or the sale of any items the sale of which is prohibited or restricted by any applicable law, including without limitation items the sale of which is prohibited or regulated by Indian law.<br>
                             l) that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;<br>
                             m) that disrupts the normal flow of dialogue with an excessive number of messages (flooding attack) to the Service, or that otherwise negatively affects other users' ability to use the Service; or<br>
                             n) that employs misleading email addresses, or forged headers or otherwise manipulated identifiers in order to disguise the origin of Content transmitted through the Service.<br><br>
                             
                             Additionally, you agree not to:<br><br>
                             o) contact anyone who has asked not to be contacted;<br>
                             p) "stalk" or otherwise harass anyone;<br>
                             q) collect personal data about other users for commercial or unlawful purposes;<br>
                             r) use automated means, including spiders, robots, crawlers, data mining tools, or the like to download data from the Service - unless expressly permitted by klx.co.in;<br>
                             s) post non-local or otherwise irrelevant Content, repeatedly post the same or similar Content or otherwise impose an unreasonable or disproportionately large load on our infrastructure;<br>
                             t) attempt to gain unauthorized access to klx.co.in's computer systems or engage in any activity that disrupts, diminishes the quality of, interferes with the performance of, or impairs the functionality of, the Service or the klx.co.in website; or<br>
                             u) use any form of automated device or computer program that enables the submission of postings on klx.co..in without each posting being manually entered by the author thereof (an "automated posting device"), including without limitation, the use of any such automated posting device to submit postings in bulk, or for automatic submission of postings at regular intervals.<br><br>
                             
                             <b>8. MARKETING COMMUNICATION</b><br>
                             Klx.co.in communicates with you as a registered member through the email id and/or mobile number that is specified in your account. We shall use this email address and/or mobile number to send you following types of communications:<br><br>
                             a) E-mails/SMS related to your account,<br>
                             b) Introduction of new services on klx.co.in and/or features in your account,<br>
                             c) Newsletters that you are subscribed to,<br>
                             d) Updates about changes in our policies,<br>
                             e) Occasional mailers of third party services.<br><br>
                             Please note that these communications may contain commercial messages of advertisers and you may be contacted by them for marketing purposes. You may opt out of the newsletters or promotional announcements anytime at your wish.<br><br>
                             
                             <b>9. OPT-OUT OF COMMUNICATION</b><br>
                             You have an option to opt-out by:<br><br>
                             a) Deleting your posts and/or other information<br>
                             b) Deactivating your account<br>
                             c) Unsubscribe from receiving marketing communications<br><br>

                             <b>10. NO SPAM POLICY</b><br>
                             You understand and agree that sending unsolicited email advertisements to klx.co.in email addresses or through klx.co.in computer systems, which is expressly prohibited by these Terms, will use or cause to be used klx.co.in servers. Any unauthorized use of classifiedz.in computer systems is a violation of these Terms and certain federal and state laws. Such violations may subject the sender and his or her agents to civil and criminal penalties.<br><br>
                             
                             <b>11. LIMITATIONS ON SERVICE</b><br>
                             You acknowledge that klx.co.in may establish limits concerning use of the Service, including the maximum number of days that Content will be retained by the Service, the maximum number and size of postings, email messages, or other Content that may be transmitted or stored by the Service, and the frequency with which you may access the Service. You agree that klx.co.in has no responsibility or liability for the deletion or failure to store any Content maintained or transmitted by the Service. You acknowledge that klx.co.in reserves the right at any time to modify or discontinue the Service (or any part thereof) with or without notice, and that klx.co.in shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.<br><br>

                             <b>12. ACCESS TO THE SERVICE</b><br>
                             Klx.co.in grants you a limited, revocable, non-exclusive license to access the Service for your own personal use. This license does not include any collection, aggregation, copying, duplication, display or derivative use of the Service nor any use of data mining, robots, spiders, or similar data gathering and extraction tools for any purpose unless expressly permitted by klx.co.in. A limited exception is provided to general purpose internet search engines and non-commercial public archives that use such tools to gather information for the sole purpose of displaying hyperlinks to the Service, provided they each do so from a stable IP address or range of IP addresses using an easily identifiable agent and comply with our robots.txt file. "General purpose internet search engine" does not include a website or search engine or other service that specializes in classified listings or in any subset of classifieds listings such as jobs, housing, for sale, services, or personals, or which is in the business of providing classified ad listing services.<br><br>
                             Klx.co.in permits you to display on your website, or create a hyperlink on your website to, individual postings on the Service so long as such use is for non-commercial and/or news reporting purposes only (e.g., for use in personal web blogs or personal online media). If the total number of such postings displayed or linked to on your website exceeds one hundred (100) postings, your use will be presumed to be in violation of these Terms, in absence of express permission granted by klx.co.in to do so. You may also create a hyperlink to the home page of klx.co.in sites so long as the link does not portray klx.co.in, its employees, or its affiliates in a false, misleading, derogatory, or otherwise offensive matter.<br><br>
                             Klx.co .in offers various parts of the Service in rss format so that users can embed individual feeds into a personal website or blog, or view postings through third party software news aggregators. Klx.co.in permits you to display, excerpt from, and link to the RSS feeds on your personal website or personal web blog, provided that (a) your use of the rss feed is for personal, non-commercial purposes only, (b) each title is correctly linked back to the original post on the Service and redirects the user to the post when the user clicks on it, (c) you provide, adjacent to the rss feed, proper attribution to 'klx.co.in' as the source, (d) your use or display does not suggest that klx.co.in promotes or endorses any third party causes, ideas, web sites, products or services, (e) you do not redistribute the rss feed, and (f) your use does not overburden klx.co.in'systems. Klx.co.in reserves all rights in the content of the rss feeds and may terminate any rss feed at any time.<br><br>
                             Use of the Service beyond the scope of authorized access granted to you by klx.co.in immediately terminates said permission or license. In order to collect, aggregate, copy, duplicate, display or make derivative use of the Service or any Content made available via the Service for other purposes (including commercial purposes) not stated herein, you must first obtain a license from klx.co.in.<br><br>

                             <b>13. TERMINATION OF SERVICE</b><br>
                             You agree that klx.co.in, in its sole discretion, has the right (but not the obligation) to delete or deactivate your account, block your email or IP address, or otherwise terminate your access to or use of the Service (or any part thereof), immediately and without notice, and remove and discard any Content within the Service, for any reason, including, without limitation, if klx.co.in believes that you have acted inconsistently with the letter or spirit of the Terms. Further, you agree that klx.co.in shall not be liable to you or any third-party for any termination of your access to the Service. Further, you agree not to attempt to use the Service after said termination. Sections 2, 4, 6 and 10-16 shall survive termination of these Terms.<br><br>

                             <b>14. PROPRIETARY RIGHTS</b><br>
                             The Service is protected to the maximum extent permitted by copyright laws and international treaties. Content displayed on or through the Service is protected by copyright as a collective work and/or compilation, pursuant to copyrights laws, and international conventions. Any reproduction, modification, creation of derivative works from or redistribution of the site or the collective work, and/or copying or reproducing the sites or any portion thereof to any other server or location for further reproduction or redistribution is prohibited without the express written consent of klx.co.in. You further agree not to reproduce, duplicate or copy Content from the Service without the express written consent of klx.co.in, and agree to abide by any and all copyright notices displayed on the Service. You may not decompile or disassemble, reverse engineer or otherwise attempt to discover any source code contained in the Service. Without limiting the foregoing, you agree not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any aspect of the Service.<br><br>
                             Although klx.co.in does not claim ownership of content that its users post, by posting Content to any public area of the Service, you automatically grant, and you represent and warrant that you have the right to grant, to klx.co.in an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, and distribute said Content and to prepare derivative works of, or incorporate into other works, said Content, and to grant and authorize sublicenses (through multiple tiers) of the foregoing. Furthermore, by posting Content to any public area of the Service, you automatically grant klx.co.in all rights necessary to prohibit any subsequent aggregation, display, copying, duplication, reproduction, or exploitation of the Content on the Service by any party for any purpose.<br><br>

                             <b>15. DISCLAIMER OF WARRANTIES</b><br>
                             YOU AGREE THAT USE OF THE KLX.CO.IN SITE AND THE SERVICE IS ENTIRELY AT YOUR OWN RISK. THE KLX.CO.IN SITE AND THE SERVICE ARE PROVIDED ON AN "AS IS" OR "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND. ALL EXPRESS AND IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS ARE EXPRESSLY DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. TO THE FULLEST EXTENT PERMITTED BY LAW, KLX.CO.IN DISCLAIMS ANY WARRANTIES FOR THE SECURITY, RELIABILITY, TIMELINESS, ACCURACY, AND PERFORMANCE OF THE KLX.CO.IN SITE AND THE SERVICE. TO THE FULLEST EXTENT PERMITTED BY LAW, cKLX.CO.IN  DISCLAIMS ANY WARRANTIES FOR OTHER SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE KLX.CO.IN SITE OR THE SITES OR SERVICE, OR ACCESSED THROUGH ANY LINKS ON THE KLX.CO.IN SITE. TO THE FULLEST EXTENT PERMITTED BY LAW, KLX.CO.IN DISCLAIMS ANY WARRANTIES FOR VIRUSES OR OTHER HARMFUL COMPONENTS IN CONNECTION WITH THE KLX.CO.IN SITE OR THE SERVICE. Some jurisdictions do not allow the disclaimer of implied warranties. In such jurisdictions, some of the foregoing disclaimers may not apply to you insofar as they relate to implied warranties.<br><br>

                             <b>16. LIMITATIONS OF LIABILITY</b><br>
                             UNDER NO CIRCUMSTANCES SHALL Klx.co.in BE LIABLE FOR DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF klx.co.in HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY ASPECT OF YOUR USE OF THE klx.co.in SITE OR THE SERVICE, WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF THE klx.co.in SITE OR THE SERVICE, FROM INABILITY TO USE THE klx.co.in SITE OR THE SERVICE, OR THE INTERRUPTION, SUSPENSION, MODIFICATION, ALTERATION, OR TERMINATION OF THE klx.co.in SITE OR THE SERVICE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE klx.co.in SITE OR THE SERVICE OR ANY LINKS ON THE klx.co.in SITE, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE klx.co.in SITE OR THE SERVICE OR ANY LINKS ON THE klx.co.in SITE. THESE LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. In some jurisdictions, limitations of liability are not permitted. In such jurisdictions, some of the foregoing limitation may not apply to you.<br><br>

                             <b>17. INDEMNITY</b><br>
                             You agree to indemnify and hold klx.co.in, its officers, subsidiaries, affiliates, successors, assigns, directors, officers, agents, service providers, suppliers and employees, harmless from any claim or demand, including reasonable attorney fees and court costs, made by any third party due to or arising out of Content you submit, post or make available through the Service, your use of the Service, your violation of the Terms, your breach of any of the representations and warranties herein, or your violation of any rights of another.<br><br>

                             <b>18. GENERAL INFORMATION</b><br>
                             The Terms constitute the entire agreement between you and klx.co.in and govern your use of the Service, superseding any prior agreements between you and klx.co.in. The Terms and the relationship between you and klx.co.in shall be governed by the Indian laws without regard to its conflict of law provisions. You and klx.co.in agree to submit to the personal and exclusive jurisdiction of the courts located within India. The failure of klx.co.in to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision. If any provision of the Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.<br><br>

                             <b>19. VIOLATION OF TERMS AND LIQUIDATED DAMAGES</b><br>
                             Please report any violations of the Terms, by flagging the posting(s) for review, or by emailing to reach@klx.co.in<br><br>
                             Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches.<br><br>
                             You understand and agree that, because damages are often difficult to quantify, if it becomes necessary for klx.co.in to pursue legal action to enforce these Terms, you will be liable to pay klx.co.in the following amounts as liquidated damages, which you accept as reasonable estimates of klx.co.in damages for the specified breaches of these Terms:<br><br>
                             a. If you post a message that (1) impersonates any person or entity; (2) falsely states or otherwise misrepresents your affiliation with a person or entity; or (3) that includes personal or identifying information about another person without that person's explicit consent, you agree to pay klx.co.in fifty thousand rupees (Rs 50000) for each such message.
                             This provision does not apply to messages that are lawful non-deceptive parodies of public figures.<br>
                             b. If klx.co.in establishes limits on the frequency with which you may access the Service, or terminates your access to or use of the Service, you agree to pay klx.co.in five hundred rupees (Rs 5,00) for each message posted in excess of such limits or for each day on which you access klx.co.in in excess of such limits, whichever is higher.<br>
                             c. If you send unsolicited email advertisements to klx.co.in email addresses or through klx.co.in computer systems, you agree to pay klx.co.in three hundred rupees (Rs 300) for each such email.<br>
                             d. If you post messages in violation of these Terms of Use, other than as described above, you agree to pay klx.co.in five thousand rupees (Rs 5,000) for each such message. In its sole discretion, klx.co.in may elect to issue a warning before assessing damages.<br>
                             e. If you aggregate, display, copy, duplicate, reproduce, or otherwise exploit for any purpose any Content (except for your own Content) in violation of these Terms without klx.co.in's express written permission, you agree to pay klx.co.in one lakh  (Rs 1,00,000) for each day on which you engage in such conduct.<br>
                             Otherwise, you agree to pay klx.co.in's actual damages, to the extent such actual damages can be reasonably calculated. Notwithstanding any other provision of these Terms, klx.co.in retains the right to seek the remedy of specific performance of any term contained in these Terms, or a preliminary or permanent injunction against the breach of any such term or in aid of the exercise of any power granted in these Terms, or any combination thereof.
                             <br><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once("footer.php"); ?>