<?php
        
	class Configuration {
		 const DATE_TIME_FROMAT = 'M d, Y H:i';
		 const DATE_FORMAT = 'M d, Y';
		 const LANGUAGE = 'la-en';
		 const TIMEZONE_CODE = 'TZ0079';
		 const TIMEZONE_VALUE = 'Asia/Kolkata';
		 const CURRENCY_CODE = 'CY0002';
		 const CURRENCY_VALUE = 'INR';
		 const EMAIL_API_ENABLE = 8;
		 const MOBILE_SMS_API_ENABLE = 9;
		 const IS_ALLOW_DUPLICATE_MOBILE = 0;
		 const IS_ALLOW_DUPLICATE_EMAIL = 0;
		 const IS_ALLOW_DUPLICATE_WHATSAPP = 0;
		 const MEMBER_LOGIN_PASSWORD_CASE_SENSITIVE = 0;
		 const MEMBER_LOGIN_PASSWORD_LENGTH = 0;
		 const MEMBER_LOGIN_PASSWORD_DURATION = 0;
		 const PROFILE_IMAGE_MINIMUM_SIZE = 0;
		 const PROFILE_IMAGE_MAXIMUM_SIZE = 0;
		 const DISPLAY_LOGIN_LAST_LOGIN = 0;
		 const SEARCH_RECORDS_PER_PAGE = 0;
		 const EMAIL_VERIFICATION_REQUIRED = 0;
		 const MOBILE_VERIFICATION_REQUIRED = 0;
		 const FRANCHISEE_LOGIN_PASSWORD_CASE_SENSITIVE = 0;
		 const FRANCHISEE_LOGIN_PASSWORD_LENGTH = 0;
		 const FRANCHISEE_LOGIN_PASSWORD_DURATION = 0;
		 const FRANCHISEE_TXN_PASSWORD_CASE_SENSITIVE = 0;
		 const FRANCHISEE_TXN_PASSWORD_LENGTH = 0;
		 const FRANCHISEE_TXN_PASSWORD_DURATION = 0;
		 const BRIDE_MAXIMUM_AGE = 0;
		 const BRIDE_MINIMUM_AGE = 0;
		 const GROOM_MAXIMUM_AGE = 0;
		 const GROOM_MINIMUM_AGE = 0;
		 const PROFILE_IMAGE_BLUR = 0;
		 const FIRST_TIME_ADD_SHORTLIST_SMS_TO_PARTNER = 0;
		 const FIRST_TIME_ADD_SHORTLIST_EMAIL_TO_PARTNER = 0;
		 const EVERY_TIME_ADD_SHORTLIST_SMS_TO_PARTNER = 0;
		 const EVERY_TIME_ADD_SHORTLIST_EMAIL_TO_PARTNER = 0;
		 const ASASASASAS = 0;
	}
?>