<div class="col-main">
                                                <div class="std"><h3 style="margin: 15px 0px 0px; padding: 0px 0px 2px; font-weight: bold; font-family: tahoma, arial, sans-serif; font-size: 11px; border: 0px; color: #000000; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;" id="sp"><a name="Shipping"></a>&nbsp;Shipping Policy</h3>
<p style="margin: 0px; padding: 5px 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">We, at Dealmaass know how important it is to receive your purchased products in the finest condition and also at your expected time, so we use a large network of couriers to deliver your products to you in the quickest time possible.</p>
<ul style="margin: 0px; padding: 0px; list-style-type: none; border: 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">For an order of Rs.500 and above, the order will be delivered at your door step free of cost.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">For an order of Rs.499 and less, a shipping charge of Rs.45 will be applicable</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">Shipping charges will not be refunded if you cancel a part of the order.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">Original shipping charges will not be refunded if you return an order delivered to you. If you self-ship the products you want to return, the shipping charges will be reimbursed based on Dealmass Returns Policy.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">
<h3 style="margin: 15px 0px 0px; padding: 0px 0px 2px; font-weight: bold; font-family: tahoma, arial, sans-serif; font-size: 11px; border: 0px; color: #000000; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;" id="cp">Cancellation Policy<a name="cancellations"></a></h3>
<p style="margin: 0px; padding: 5px 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">Dealmaass reserves the right to cancel any order without any explanation for doing so, as per the circumstances where the requirement could not be met. The company will ensure that any communication of cancellation of an order or any applicable refund will be made in reasonable time.</p>
</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">
<h3 style="margin: 15px 0px 0px; padding: 0px 0px 2px; font-weight: bold; font-family: tahoma, arial, sans-serif; font-size: 11px; border: 0px; color: #000000; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;" id="rp">Return Policy</h3>
<p style="margin: 0px; padding: 5px 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">We have 30-days Return Policy, which is applicable under these circumstances:</p>
<ul style="margin: 0px; padding: 0px; list-style-type: none; border: 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">If broken/unsealed, do not accept the order at the time of delivery itself.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">In the case of merchandise, returned products must be unused and returned with all original packaging and tags that they were shipped with.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">All items to be returned must be<span class="Apple-converted-space">&nbsp;</span><strong style="margin: 0px; padding: 0px; font-weight: bold;">unused and in their original condition</strong><span class="Apple-converted-space">&nbsp;</span>with all original tags and packaging intact.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">Please take care to pack items securely and safely to prevent any loss or damage during transit. For all self shipped returns, please use a reliable courier service.</li>
</ul>
<h3 style="margin: 15px 0px 0px; padding: 0px 0px 2px; font-weight: bold; font-family: tahoma, arial, sans-serif; font-size: 11px; border: 0px; color: #000000; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;" id="cod"><a name="Shipping"></a>Cash On Delivery Policy</h3>
<p style="margin: 0px; padding: 5px 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">As per the Cash on Delivery policy:</p>
<ul style="margin: 0px; padding: 0px; list-style-type: none; border: 0px; color: #464545; font-family: tahoma, Arial, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;">
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">A 'Cash on Delivery' order is placed only once verified by Dealmaass Customer Support via mail/sms/telecom.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">To avail C-o-D Service, all the items in the cart should be applicable for C-o-D.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">Promo Code/Coupon code discounts is not allowed on a C-o-D order.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">C-o-D is applicable on a minimum purchase of<span class="Apple-converted-space">&nbsp;</span><span style="margin: 0px 2px; padding: 0px; border: 0px; display: inline-block; font-size: 12px; font-weight: normal;" class="WebRupee">Rs.</span>500 and maximum of<span class="Apple-converted-space">&nbsp;</span><span style="margin: 0px 2px; padding: 0px; border: 0px; display: inline-block; font-size: 12px; font-weight: normal;" class="WebRupee">Rs.</span><span class="Apple-converted-space">&nbsp;</span>5000 only.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">Pin code provided for Cash on Delivery should be in the serviceable area. If not, online order has to be placed.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">You cannot open the box without making the payment at the time of delivery.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;">If the product is open, do not accept the order.</li>
<li style="margin: 0px 0px 5px 1px; padding: 0px 0px 4px 11px; border: 0px; list-style-type: none; background-image: url('http://images.kooves.com/images/kv/bulletrarw.png'); background-attachment: scroll; background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><span style="color: #4c4c4c; font-family: Arial,Helvetica,sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; background-color: #ffffff; display: inline ! important; float: none;">Only Cash payment is accepted for COD orders. Payment through cheque, demand draft or credit/debit card will not be accepted.</span></li>
</ul>
</li>
</ul></div>                    </div>